
import { Language, SubjectDef } from './types';

// Fallback Subjects in case DB is empty
export const SUBJECTS_DATA: SubjectDef[] = [
  { id: 'math', translations: { it: 'Matematica', es: 'Matemáticas', en: 'Math', fr: 'Maths', de: 'Mathe' }, color: 'bg-blue-100 text-blue-800', icon: '➗' },
  { id: 'physics', translations: { it: 'Fisica', es: 'Física', en: 'Physics', fr: 'Physique', de: 'Physik' }, color: 'bg-red-100 text-red-800', icon: '⚛️' },
  { id: 'english', translations: { it: 'Inglese', es: 'Inglés', en: 'English', fr: 'Anglais', de: 'Englisch' }, color: 'bg-sky-100 text-sky-800', icon: '🇬🇧' },
  { id: 'spanish', translations: { it: 'Spagnolo', es: 'Español', en: 'Spanish', fr: 'Espagnol', de: 'Spanisch' }, color: 'bg-yellow-100 text-yellow-800', icon: '🇪🇸' },
  { id: 'geography', translations: { it: 'Geografia', es: 'Geografía', en: 'Geography', fr: 'Géographie', de: 'Geografie' }, color: 'bg-emerald-100 text-emerald-800', icon: '🌍' },
  { id: 'law', translations: { it: 'Diritto', es: 'Derecho', en: 'Law', fr: 'Droit', "de": 'Recht' }, color: 'bg-slate-100 text-slate-800', icon: '⚖️' },
  { id: 'italian_l2', translations: { it: 'Italiano per Stranieri', es: 'Italiano para Extranjeros', en: 'Italian L2', fr: 'Italien L2', de: 'Italienisch L2' }, color: 'bg-green-50 text-green-700', icon: '🇮🇹' },
  { id: 'german', translations: { it: 'Tedesco', es: 'Alemán', en: 'German', fr: 'Allemand', de: 'Deutsch' }, color: 'bg-orange-100 text-orange-800', icon: '🇩🇪' },
];

export const DICTIONARY: Record<Language, Record<string, string>> = {
  it: {
    welcome: 'Portale Doposcuola',
    login: 'Accedi al Portale',
    register: 'Nuova Iscrizione',
    email: 'Indirizzo Email',
    password: 'Password',
    name: 'Nome e Cognome',
    phone: 'Numero di Telefono',
    age: 'Età',
    role: 'Sei un Docente o Studente?',
    student: 'Studente',
    teacher: 'Docente',
    leader: 'Coordinatore',
    loginButton: 'Entra nel sistema',
    registerButton: 'Registrati Ora',
    parentName: 'Nome del Tutore/Genitore',
    parentEmail: 'Email del Tutore',
    gdprNotice: 'In conformità con il GDPR, per i minori di 16 anni è richiesto il consenso dei genitori.',
    mfaCode: 'Codice OTP (inviato via email)',
    verify: 'Verifica Identità',
    dashboard: 'Dashboard',
    bookClass: 'Prenota le tue lezioni',
    myClasses: 'Le mie attività',
    availableClasses: 'Richieste Studenti',
    claim: 'Prendi in carico',
    notes: 'Registro / Note',
    announcements: 'Bacheca Avvisi',
    newAnnouncement: 'Nuovo Avviso',
    send: 'Pubblica',
    logout: 'Disconnetti',
    selectDate: 'Scegli la data',
    selectSubject: 'Scegli la materia',
    noClasses: 'Nessuna attività programmata.',
    booked: 'Prenotata',
    claimedBy: 'Docente:',
    subject: 'Materia',
    date: 'Data',
    saveNotes: 'Salva nel registro',
    loading: 'Elaborazione...',
    adminPanel: 'Amministrazione',
    manageLeaders: 'Gestione Coordinatori',
    promoteToLeader: 'Nomina Coordinatore',
    demoteLeader: 'Rimuovi Coordinatore',
    isLeader: 'Coordinatore',
    reports: 'Resoconto Giornaliero',
    printReport: 'Stampa Resoconto',
    maxSubjects: 'Massimo 2 materie per giorno.',
    alreadyBooked: 'Sei già iscritto a questa materia oggi.',
    selectSubjectTitle: 'Cosa vuoi studiare?',
    availableSlots: 'Slot Disponibili',
    confirmBooking: 'Conferma Prenotazione',
    unclaimed: 'Non Assegnato',
    generatedBy: 'Generato dal sistema Doposcuola Connect',
    superAdmin: 'Amministratore Unico',
    cancelBooking: 'Cancella Prenotazione',
    releaseClass: 'Rilascia Classe',
    dob: 'Data di Nascita',
    pendingApproval: 'Account in attesa di approvazione.',
    accountActive: 'Account Attivo',
    approve: 'Approva',
    pendingRequests: 'Richieste Pendenti',
    cantAccess: 'Non riesco ad accedere?',
    recoverPassword: 'Recupera Password',
    sendRecoveryLink: 'Invia Link di Recupero',
    backToLogin: 'Torna al Login',
    loginWithPassword: 'USA PASSWORD',
    loginWithOtp: 'USA LINK/OTP',
    setNewPassword: 'Imposta Nuova Password',
    passwordUpdated: 'Password aggiornata con successo!',
    enterNewPassword: 'Inserisci la nuova password',
    updatePassword: 'Aggiorna Password',
    manageHolidays: 'Gestione Festività',
    addHoliday: 'Aggiungi Festività',
    manageUsers: 'Gestione Utenti',
    manageSubjects: 'Gestione Materie',
    settings: 'Impostazioni',
    deleteUser: 'Elimina Utente',
    attendance: 'Presenze',
    markPresent: 'Presente',
    markAbsent: 'Assente',
    status: 'Stato',
    addSubject: 'Aggiungi Materia',
    subjectName: 'Nome Materia',
    icon: 'Icona',
    color: 'Colore',
    preview: 'Anteprima',
    save: 'Salva',
    delete: 'Elimina',
    reportsAdvanced: 'Report Avanzati',
    filterByTeacher: 'Filtra per Docente',
    filterBySubject: 'Filtra per Materia',
    showAbsencesOnly: 'Mostra solo Assenze',
    devMode: '🚧 App in fase di sviluppo (Beta)',
    checkEmail: 'Controlla la tua email',
    resendCodeIn: 'Invia di nuovo tra',
    resendCodeBtn: 'Invia nuovo codice',
    changeEmail: 'Cambia Email / Indietro',
    errorLinkSent: 'Link inviato! Controlla la tua email.',
    errorResent: 'Codice rinviato! Controlla la tua email.',
    errInvalidCreds: 'Credenziali non valide.',
    errRateLimit: 'Troppi tentativi. Riprova più tardi.',
    errCodeExpired: 'Codice scaduto o non valido.',
    errParentRequired: 'Dettagli genitore richiesti.',
    errRegistrationFailed: 'Registrazione fallita.',
    enterEmailRecovery: 'Inserisci la tua email per ricevere il link.',
    copyEmails: 'Copia Lista Email',
    emailsCopied: 'Email copiate! Incolla in CCO.',
    // Colors
    col_blue: 'Blu',
    col_red: 'Rosso',
    col_green: 'Verde',
    col_yellow: 'Giallo',
    col_purple: 'Viola',
    col_pink: 'Rosa',
    col_orange: 'Arancione',
    col_gray: 'Grigio',
  },
  en: {
    welcome: 'After-School Portal',
    login: 'Portal Login',
    register: 'New Registration',
    email: 'Email Address',
    password: 'Password',
    name: 'Full Name',
    phone: 'Phone Number',
    age: 'Age',
    role: 'Are you a Teacher or Student?',
    student: 'Student',
    teacher: 'Teacher',
    leader: 'Coordinator',
    loginButton: 'Enter System',
    registerButton: 'Register Now',
    parentName: 'Guardian Name',
    parentEmail: 'Guardian Email',
    gdprNotice: 'In compliance with GDPR, parental consent is required for users under 16.',
    mfaCode: 'OTP Code (sent via email)',
    verify: 'Verify Identity',
    dashboard: 'Dashboard',
    bookClass: 'Book Your Classes',
    myClasses: 'My Activities',
    availableClasses: 'Student Requests',
    claim: 'Take Charge',
    notes: 'Log / Notes',
    announcements: 'Notice Board',
    newAnnouncement: 'New Notice',
    send: 'Publish',
    logout: 'Disconnect',
    selectDate: 'Choose Date',
    selectSubject: 'Choose Subject',
    noClasses: 'No scheduled activities.',
    booked: 'Booked',
    claimedBy: 'Teacher:',
    subject: 'Subject',
    date: 'Date',
    saveNotes: 'Save to Log',
    loading: 'Processing...',
    adminPanel: 'Administration',
    manageLeaders: 'Manage Coordinators',
    promoteToLeader: 'Appoint Coordinator',
    demoteLeader: 'Remove Coordinator',
    isLeader: 'Coordinator',
    reports: 'Daily Reports',
    printReport: 'Print Report',
    maxSubjects: 'Maximum 2 subjects per day.',
    alreadyBooked: 'You are already booked for this subject today.',
    selectSubjectTitle: 'What do you want to study?',
    availableSlots: 'Available Slots',
    confirmBooking: 'Confirm Booking',
    unclaimed: 'Unclaimed',
    generatedBy: 'Generated by Doposcuola Connect System',
    superAdmin: 'Super Admin',
    cancelBooking: 'Cancel Booking',
    releaseClass: 'Release Class',
    dob: 'Date of Birth',
    pendingApproval: 'Account pending approval.',
    accountActive: 'Account Active',
    approve: 'Approve',
    pendingRequests: 'Pending Requests',
    cantAccess: "Can't access?",
    recoverPassword: 'Recover Password',
    sendRecoveryLink: 'Send Recovery Link',
    backToLogin: 'Back to Login',
    loginWithPassword: 'USE PASSWORD',
    loginWithOtp: 'USE LINK/OTP',
    setNewPassword: 'Set New Password',
    passwordUpdated: 'Password updated successfully!',
    enterNewPassword: 'Enter new password',
    updatePassword: 'Update Password',
    manageHolidays: 'Holiday Management',
    addHoliday: 'Add Holiday',
    manageUsers: 'Manage Users',
    manageSubjects: 'Manage Subjects',
    settings: 'Settings',
    deleteUser: 'Delete User',
    attendance: 'Attendance',
    markPresent: 'Present',
    markAbsent: 'Absent',
    status: 'Status',
    addSubject: 'Add Subject',
    subjectName: 'Subject Name',
    icon: 'Icon',
    color: 'Color',
    preview: 'Preview',
    save: 'Save',
    delete: 'Delete',
    reportsAdvanced: 'Advanced Reports',
    filterByTeacher: 'Filter by Teacher',
    filterBySubject: 'Filter by Subject',
    showAbsencesOnly: 'Show Absences Only',
    devMode: '🚧 App in Development (Beta)',
    checkEmail: 'Check your email',
    resendCodeIn: 'Resend code in',
    resendCodeBtn: 'Resend Code',
    changeEmail: 'Change Email / Back',
    errorLinkSent: 'Link sent! Check your email.',
    errorResent: 'Code resent! Check your email.',
    errInvalidCreds: 'Invalid credentials.',
    errRateLimit: 'Rate limit exceeded. Try again later.',
    errCodeExpired: 'Code expired or invalid.',
    errParentRequired: 'Parent details required.',
    errRegistrationFailed: 'Registration failed.',
    enterEmailRecovery: 'Enter your email to receive a reset link.',
    copyEmails: 'Copy Email List',
    emailsCopied: 'Emails copied! Paste into BCC.',
    // Colors
    col_blue: 'Blue',
    col_red: 'Red',
    col_green: 'Green',
    col_yellow: 'Yellow',
    col_purple: 'Purple',
    col_pink: 'Pink',
    col_orange: 'Orange',
    col_gray: 'Gray',
  },
  es: {
    welcome: 'Portal Doposcuola',
    login: 'Acceso al Portal',
    register: 'Nueva Inscripción',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    name: 'Nombre Completo',
    phone: 'Teléfono',
    age: 'Edad',
    role: '¿Eres Docente o Alumno?',
    student: 'Alumno',
    teacher: 'Docente',
    leader: 'Coordinador',
    loginButton: 'Entrar al Sistema',
    registerButton: 'Registrarse Ahora',
    parentName: 'Nombre del Tutor',
    parentEmail: 'Email del Tutor',
    gdprNotice: 'En cumplimiento con GDPR, se requiere consentimiento parental para menores de 16.',
    mfaCode: 'Código OTP (enviado por email)',
    verify: 'Verificar Identidad',
    dashboard: 'Tablero',
    bookClass: 'Reservar Clases',
    myClasses: 'Mis Actividades',
    availableClasses: 'Solicitudes de Alumnos',
    claim: 'Asignarme',
    notes: 'Registro / Notas',
    announcements: 'Tablón de Anuncios',
    newAnnouncement: 'Nuevo Aviso',
    send: 'Publicar',
    logout: 'Desconectar',
    selectDate: 'Elegir Fecha',
    selectSubject: 'Elegir Materia',
    noClasses: 'No hay actividades programadas.',
    booked: 'Reservado',
    claimedBy: 'Docente:',
    subject: 'Materia',
    date: 'Fecha',
    saveNotes: 'Guardar en Registro',
    loading: 'Procesando...',
    adminPanel: 'Administración',
    manageLeaders: 'Gestión de Coordinadores',
    promoteToLeader: 'Nombrar Coordinador',
    demoteLeader: 'Remover Coordinador',
    isLeader: 'Coordinador',
    reports: 'Reporte Diario',
    printReport: 'Imprimir Reporte',
    maxSubjects: 'Máximo 2 materias por día.',
    alreadyBooked: 'Ya estás inscrito en esta materia hoy.',
    selectSubjectTitle: '¿Qué quieres estudiar?',
    availableSlots: 'Turnos Disponibles',
    confirmBooking: 'Confirmar Reserva',
    unclaimed: 'Sin Asignar',
    generatedBy: 'Generado por sistema Doposcuola Connect',
    superAdmin: 'Super Admin',
    cancelBooking: 'Cancelar Reserva',
    releaseClass: 'Liberar Clase',
    dob: 'Fecha de Nacimiento',
    pendingApproval: 'Cuenta pendiente de aprobación.',
    accountActive: 'Cuenta Activa',
    approve: 'Aprobar',
    pendingRequests: 'Solicitudes Pendientes',
    cantAccess: '¿No puedes acceder?',
    recoverPassword: 'Recuperar Contraseña',
    sendRecoveryLink: 'Enviar Enlace',
    backToLogin: 'Volver al Login',
    loginWithPassword: 'USAR CONTRASEÑA',
    loginWithOtp: 'USAR LINK/OTP',
    setNewPassword: 'Crear Nueva Contraseña',
    passwordUpdated: '¡Contraseña actualizada con éxito!',
    enterNewPassword: 'Ingresa nueva contraseña',
    updatePassword: 'Actualizar Contraseña',
    manageHolidays: 'Gestión de Feriados',
    addHoliday: 'Agregar Feriado',
    manageUsers: 'Gestión de Usuarios',
    manageSubjects: 'Gestión de Materias',
    settings: 'Configuración',
    deleteUser: 'Eliminar Usuario',
    attendance: 'Asistencia',
    markPresent: 'Presente',
    markAbsent: 'Ausente',
    status: 'Estado',
    addSubject: 'Nueva Materia',
    subjectName: 'Nombre Materia',
    icon: 'Icono',
    color: 'Color',
    preview: 'Vista Previa',
    save: 'Guardar',
    delete: 'Borrar',
    reportsAdvanced: 'Reportes Avanzados',
    filterByTeacher: 'Filtrar por Docente',
    filterBySubject: 'Filtrar por Materia',
    showAbsencesOnly: 'Solo Ausencias',
    devMode: '🚧 App en Desarrollo (Beta)',
    checkEmail: 'Revisa tu email',
    resendCodeIn: 'Reenviar en',
    resendCodeBtn: 'Reenviar Código',
    changeEmail: 'Cambiar Email / Volver',
    errorLinkSent: '¡Enlace enviado! Revisa tu email.',
    errorResent: '¡Código reenviado! Revisa tu email.',
    errInvalidCreds: 'Credenciales inválidas.',
    errRateLimit: 'Límite excedido. Intenta más tarde.',
    errCodeExpired: 'Código expirado o inválido.',
    errParentRequired: 'Datos del tutor requeridos.',
    errRegistrationFailed: 'Fallo en registro.',
    enterEmailRecovery: 'Ingresa tu email para recibir el enlace.',
    copyEmails: 'Copiar Lista Email',
    emailsCopied: '¡Copiado! Pega en CCO.',
    // Colors
    col_blue: 'Azul',
    col_red: 'Rojo',
    col_green: 'Verde',
    col_yellow: 'Amarillo',
    col_purple: 'Morado',
    col_pink: 'Rosa',
    col_orange: 'Naranja',
    col_gray: 'Gris',
  },
  fr: {
    welcome: 'Portail Doposcuola',
    login: 'Connexion Portail',
    register: 'Nouvelle Inscription',
    email: 'Adresse Email',
    password: 'Mot de passe',
    name: 'Nom Complet',
    phone: 'Téléphone',
    age: 'Âge',
    role: 'Êtes-vous Enseignant ou Élève ?',
    student: 'Élève',
    teacher: 'Enseignant',
    leader: 'Coordinateur',
    loginButton: 'Entrer dans le système',
    registerButton: 'S\'inscrire maintenant',
    parentName: 'Nom du Tuteur',
    parentEmail: 'Email du Tuteur',
    gdprNotice: 'Conformément au RGPD, le consentement parental est requis pour les moins de 16 ans.',
    mfaCode: 'Code OTP (envoyé par email)',
    verify: 'Vérifier l\'identité',
    dashboard: 'Tableau de bord',
    bookClass: 'Réserver vos cours',
    myClasses: 'Mes Activités',
    availableClasses: 'Demandes des élèves',
    claim: 'Prendre en charge',
    notes: 'Registre / Notes',
    announcements: 'Tableau d\'affichage',
    newAnnouncement: 'Nouvel Avis',
    send: 'Publier',
    logout: 'Déconnexion',
    selectDate: 'Choisir la date',
    selectSubject: 'Choisir la matière',
    noClasses: 'Aucune activité prévue.',
    booked: 'Réservé',
    claimedBy: 'Enseignant :',
    subject: 'Matière',
    date: 'Date',
    saveNotes: 'Enregistrer au registre',
    loading: 'Traitement...',
    adminPanel: 'Administration',
    manageLeaders: 'Gérer les Coordinateurs',
    promoteToLeader: 'Nommer Coordinateur',
    demoteLeader: 'Retirer Coordinateur',
    isLeader: 'Coordinateur',
    reports: 'Rapport Quotidien',
    printReport: 'Imprimer le Rapport',
    maxSubjects: 'Maximum 2 matières par jour.',
    alreadyBooked: 'Vous êtes déjà inscrit à cette matière aujourd\'hui.',
    selectSubjectTitle: 'Que voulez-vous étudier ?',
    availableSlots: 'Créneaux Disponibles',
    confirmBooking: 'Confirmer la Réservation',
    unclaimed: 'Non Attribué',
    generatedBy: 'Généré par le système Doposcuola Connect',
    superAdmin: 'Super Admin',
    cancelBooking: 'Annuler la réservation',
    releaseClass: 'Libérer le cours',
    dob: 'Date de Naissance',
    pendingApproval: 'Compte en attente d\'approbation.',
    accountActive: 'Compte Actif',
    approve: 'Approuver',
    pendingRequests: 'Demandes en attente',
    cantAccess: 'Problème de connexion ?',
    recoverPassword: 'Récupérer Mot de Passe',
    sendRecoveryLink: 'Envoyer Lien',
    backToLogin: 'Retour Connexion',
    loginWithPassword: 'MOT DE PASSE',
    loginWithOtp: 'LIEN/CODE',
    setNewPassword: 'Nouveau mot de passe',
    passwordUpdated: 'Mot de passe mis à jour !',
    enterNewPassword: 'Entrez le nouveau mot de passe',
    updatePassword: 'Mettre à jour',
    manageHolidays: 'Gestion des Vacances',
    addHoliday: 'Ajouter Vacances',
    manageUsers: 'Gérer les utilisateurs',
    manageSubjects: 'Gérer les matières',
    settings: 'Paramètres',
    deleteUser: 'Supprimer',
    attendance: 'Présence',
    markPresent: 'Présent',
    markAbsent: 'Absent',
    status: 'Statut',
    addSubject: 'Ajouter Matière',
    subjectName: 'Nom Matière',
    icon: 'Icône',
    color: 'Couleur',
    preview: 'Aperçu',
    save: 'Sauvegarder',
    delete: 'Supprimer',
    reportsAdvanced: 'Rapports Avancés',
    filterByTeacher: 'Filtrer par Enseignant',
    filterBySubject: 'Filtrer par Matière',
    showAbsencesOnly: 'Voir Absences',
    devMode: '🚧 Application en développement (Bêta)',
    checkEmail: 'Vérifiez votre email',
    resendCodeIn: 'Renvoyer dans',
    resendCodeBtn: 'Renvoyer le code',
    changeEmail: 'Changer Email / Retour',
    errorLinkSent: 'Lien envoyé ! Vérifiez votre email.',
    errorResent: 'Code renvoyé ! Vérifiez votre email.',
    errInvalidCreds: 'Identifiants invalides.',
    errRateLimit: 'Limite dépassée. Réessayez plus tard.',
    errCodeExpired: 'Code expiré ou invalide.',
    errParentRequired: 'Détails du parent requis.',
    errRegistrationFailed: 'Échec de l\'inscription.',
    enterEmailRecovery: 'Entrez votre email pour recevoir le lien.',
    copyEmails: 'Copier Emails',
    emailsCopied: 'Copié ! Coller en Cci.',
    // Colors
    col_blue: 'Bleu',
    col_red: 'Rouge',
    col_green: 'Vert',
    col_yellow: 'Jaune',
    col_purple: 'Violet',
    col_pink: 'Rose',
    col_orange: 'Orange',
    col_gray: 'Gris',
  },
  de: {
    welcome: 'Doposcuola Portal',
    login: 'Portal Login',
    register: 'Neue Registrierung',
    email: 'E-Mail-Adresse',
    password: 'Passwort',
    name: 'Vollständiger Name',
    phone: 'Telefonnummer',
    age: 'Alter',
    role: 'Sind Sie Lehrer oder Schüler?',
    student: 'Schüler',
    teacher: 'Lehrer',
    leader: 'Koordinator',
    loginButton: 'System betreten',
    registerButton: 'Jetzt registrieren',
    parentName: 'Name des Erziehungsberechtigten',
    parentEmail: 'E-Mail des Erziehungsberechtigten',
    gdprNotice: 'Gemäß DSGVO ist für unter 16-Jährige die Zustimmung der Eltern erforderlich.',
    mfaCode: 'OTP-Code (per E-Mail gesendet)',
    verify: 'Identität überprüfen',
    dashboard: 'Dashboard',
    bookClass: 'Kurse buchen',
    myClasses: 'Meine Aktivitäten',
    availableClasses: 'Schüleranfragen',
    claim: 'Übernehmen',
    notes: 'Logbuch / Notizen',
    announcements: 'Schwarzes Brett',
    newAnnouncement: 'Neue Mitteilung',
    send: 'Veröffentlichen',
    logout: 'Abmelden',
    selectDate: 'Datum wählen',
    selectSubject: 'Fach wählen',
    noClasses: 'Keine Aktivitäten geplant.',
    booked: 'Gebucht',
    claimedBy: 'Lehrer:',
    subject: 'Fach',
    date: 'Datum',
    saveNotes: 'Im Logbuch speichern',
    loading: 'Verarbeitung...',
    adminPanel: 'Verwaltung',
    manageLeaders: 'Koordinatoren verwalten',
    promoteToLeader: 'Koordinator ernennen',
    demoteLeader: 'Koordinator entfernen',
    isLeader: 'Koordinator',
    reports: 'Tagesbericht',
    printReport: 'Bericht drucken',
    maxSubjects: 'Maximal 2 Fächer pro Tag.',
    alreadyBooked: 'Sie sind heute bereits für dieses Fach angemeldet.',
    selectSubjectTitle: 'Was möchten Sie lernen?',
    availableSlots: 'Verfügbare Plätze',
    confirmBooking: 'Buchung bestätigen',
    unclaimed: 'Nicht zugewiesen',
    generatedBy: 'Generiert vom Doposcuola Connect System',
    superAdmin: 'Super Admin',
    cancelBooking: 'Buchung stornieren',
    releaseClass: 'Klasse freigeben',
    dob: 'Geburtsdatum',
    pendingApproval: 'Konto wartet auf Genehmigung.',
    accountActive: 'Konto Aktiv',
    approve: 'Genehmigen',
    pendingRequests: 'Ausstehende Anfragen',
    cantAccess: 'Zugangsprobleme?',
    recoverPassword: 'Passwort wiederherstellen',
    sendRecoveryLink: 'Link senden',
    backToLogin: 'Zurück zum Login',
    loginWithPassword: 'MIT PASSWORT',
    loginWithOtp: 'MIT LINK/CODE',
    setNewPassword: 'Neues Passwort setzen',
    passwordUpdated: 'Passwort erfolgreich aktualisiert!',
    enterNewPassword: 'Neues Passwort eingeben',
    updatePassword: 'Passwort aktualisieren',
    manageHolidays: 'Feiertagsmanagement',
    addHoliday: 'Feiertag hinzufügen',
    manageUsers: 'Benutzer verwalten',
    manageSubjects: 'Fächer verwalten',
    settings: 'Einstellungen',
    deleteUser: 'Benutzer löschen',
    attendance: 'Anwesenheit',
    markPresent: 'Anwesend',
    markAbsent: 'Abwesend',
    status: 'Status',
    addSubject: 'Fach hinzufügen',
    subjectName: 'Fachname',
    icon: 'Icon',
    color: 'Farbe',
    preview: 'Vorschau',
    save: 'Speichern',
    delete: 'Löschen',
    reportsAdvanced: 'Erweiterte Berichte',
    filterByTeacher: 'Lehrer filtern',
    filterBySubject: 'Fach filtern',
    showAbsencesOnly: 'Nur Abwesenheiten',
    devMode: '🚧 App in Entwicklung (Beta)',
    checkEmail: 'E-Mail prüfen',
    resendCodeIn: 'Neuer Code in',
    resendCodeBtn: 'Code erneut senden',
    changeEmail: 'E-Mail ändern / Zurück',
    errorLinkSent: 'Link gesendet! E-Mail prüfen.',
    errorResent: 'Code gesendet! E-Mail prüfen.',
    errInvalidCreds: 'Ungültige Zugangsdaten.',
    errRateLimit: 'Limit erreicht. Später versuchen.',
    errCodeExpired: 'Code abgelaufen oder ungültig.',
    errParentRequired: 'Elterndaten erforderlich.',
    errRegistrationFailed: 'Registrierung fehlgeschlagen.',
    enterEmailRecovery: 'Geben Sie Ihre E-Mail ein.',
    copyEmails: 'E-Mails kopieren',
    emailsCopied: 'Kopiert! In BCC einfügen.',
    // Colors
    col_blue: 'Blau',
    col_red: 'Rot',
    col_green: 'Grün',
    col_yellow: 'Gelb',
    col_purple: 'Lila',
    col_pink: 'Rosa',
    col_orange: 'Orange',
    col_gray: 'Grau',
  }
};
