
import { Language, SubjectDef } from './types';

// Data extraction from the uploaded image (Handwritten note)
export const SUBJECTS_DATA: SubjectDef[] = [
  { 
    id: 'math_middle', 
    translations: { it: 'Matematica (Medie)', es: 'Matemáticas (Media)', en: 'Math (Middle School)', fr: 'Maths (Collège)', de: 'Mathe (Mittelstufe)' },
    color: 'bg-blue-100 text-blue-800 border-blue-200',
    icon: '➗'
  },
  { 
    id: 'math_biennio', 
    translations: { it: 'Matematica (Biennio)', es: 'Matemáticas (1-2 Sup)', en: 'Math (High School 1-2)', fr: 'Maths (Lycée 1-2)', de: 'Mathe (Oberstufe 1-2)' },
    color: 'bg-indigo-100 text-indigo-800 border-indigo-200',
    icon: '📐'
  },
  { 
    id: 'math_triennio', 
    translations: { it: 'Matematica (Triennio)', es: 'Matemáticas (3-5 Sup)', en: 'Math (High School 3-5)', fr: 'Maths (Lycée 3-5)', de: 'Mathe (Oberstufe 3-5)' },
    color: 'bg-purple-100 text-purple-800 border-purple-200',
    icon: '📈'
  },
  { 
    id: 'physics', 
    translations: { it: 'Fisica', es: 'Física', en: 'Physics', fr: 'Physique', de: 'Physik' },
    color: 'bg-red-100 text-red-800 border-red-200',
    icon: '⚛️'
  },
  { 
    id: 'chemistry', 
    translations: { it: 'Chimica', es: 'Química', en: 'Chemistry', fr: 'Chimie', de: 'Chemie' },
    color: 'bg-pink-100 text-pink-800 border-pink-200',
    icon: '🧪'
  },
  { 
    id: 'italian', 
    translations: { it: 'Italiano', es: 'Italiano', en: 'Italian', fr: 'Italien', de: 'Italienisch' },
    color: 'bg-green-100 text-green-800 border-green-200',
    icon: '🇮🇹'
  },
  { 
    id: 'italian_foreign', 
    translations: { it: 'Lingua Ital. per Stranieri', es: 'Italiano para Extranjeros', en: 'Italian for Foreigners', fr: 'Italien pour Étrangers', de: 'Italienisch für Ausländer' },
    color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    icon: '🌍'
  },
  { 
    id: 'english', 
    translations: { it: 'Inglese', es: 'Inglés', en: 'English', fr: 'Anglais', de: 'Englisch' },
    color: 'bg-sky-100 text-sky-800 border-sky-200',
    icon: '🇬🇧'
  },
  { 
    id: 'french', 
    translations: { it: 'Francese', es: 'Francés', en: 'French', fr: 'Français', de: 'Französisch' },
    color: 'bg-cyan-100 text-cyan-800 border-cyan-200',
    icon: '🇫🇷'
  },
  { 
    id: 'spanish', 
    translations: { it: 'Spagnolo', es: 'Español', en: 'Spanish', fr: 'Espagnol', de: 'Spanisch' },
    color: 'bg-orange-100 text-orange-800 border-orange-200',
    icon: '🇪🇸'
  },
  { 
    id: 'german', 
    translations: { it: 'Tedesco', es: 'Alemán', en: 'German', fr: 'Allemand', de: 'Deutsch' },
    color: 'bg-yellow-100 text-yellow-800 border-yellow-200',
    icon: '🇩🇪'
  },
  { 
    id: 'history', 
    translations: { it: 'Storia', es: 'Historia', en: 'History', fr: 'Histoire', de: 'Geschichte' },
    color: 'bg-amber-100 text-amber-800 border-amber-200',
    icon: '📜'
  },
  { 
    id: 'geography', 
    translations: { it: 'Geografia', es: 'Geografía', en: 'Geography', fr: 'Géographie', de: 'Geografie' },
    color: 'bg-lime-100 text-lime-800 border-lime-200',
    icon: '🗺️'
  },
  { 
    id: 'law', 
    translations: { it: 'Diritto', es: 'Derecho', en: 'Law', fr: 'Droit', de: 'Recht' },
    color: 'bg-slate-100 text-slate-800 border-slate-200',
    icon: '⚖️'
  },
];

export const DICTIONARY: Record<Language, Record<string, string>> = {
  it: {
    welcome: 'Portale Doposcuola',
    login: 'Accedi al Portale',
    register: 'Nuova Iscrizione',
    email: 'Indirizzo Email',
    password: 'Password',
    name: 'Nome e Cognome',
    phone: 'Numero di Telefono',
    age: 'Età',
    role: 'Sei un Docente o Studente?',
    student: 'Studente',
    teacher: 'Docente',
    leader: 'Coordinatore',
    loginButton: 'Entra nel sistema',
    registerButton: 'Registrati Ora',
    parentName: 'Nome del Tutore/Genitore',
    parentEmail: 'Email del Tutore',
    gdprNotice: 'In conformità con il GDPR, per i minori di 16 anni è richiesto il consenso dei genitori.',
    mfaCode: 'Codice OTP (inviato via email)',
    verify: 'Verifica Identità',
    dashboard: 'Dashboard',
    bookClass: 'Prenota le tue lezioni',
    myClasses: 'Le mie attività',
    availableClasses: 'Richieste Studenti',
    claim: 'Prendi in carico',
    notes: 'Registro / Note',
    announcements: 'Bacheca Avvisi',
    newAnnouncement: 'Nuovo Avviso',
    send: 'Pubblica',
    logout: 'Disconnetti',
    selectDate: 'Scegli la data',
    selectSubject: 'Scegli la materia',
    noClasses: 'Nessuna attività programmata.',
    booked: 'Prenotata',
    claimedBy: 'Docente:',
    subject: 'Materia',
    date: 'Data',
    saveNotes: 'Salva nel registro',
    loading: 'Elaborazione...',
    adminPanel: 'Amministrazione',
    manageLeaders: 'Gestione Coordinatori',
    promoteToLeader: 'Nomina Coordinatore',
    demoteLeader: 'Rimuovi Coordinatore',
    isLeader: 'Coordinatore',
    reports: 'Resoconto Giornaliero',
    printReport: 'Stampa Resoconto',
    maxSubjects: 'Massimo 2 materie per giorno.',
    alreadyBooked: 'Sei già iscritto a questa materia oggi.',
    selectSubjectTitle: 'Cosa vuoi studiare?',
    availableSlots: 'Slot Disponibili',
    confirmBooking: 'Conferma Prenotazione',
    unclaimed: 'Non Assegnato',
    generatedBy: 'Generato dal sistema Doposcuola Connect',
    superAdmin: 'Amministratore Unico',
    cancelBooking: 'Cancella Prenotazione',
    releaseClass: 'Rilascia Classe'
  },
  en: {
    welcome: 'After-School Portal',
    login: 'Portal Login',
    register: 'New Registration',
    email: 'Email Address',
    password: 'Password',
    name: 'Full Name',
    phone: 'Phone Number',
    age: 'Age',
    role: 'Are you a Teacher or Student?',
    student: 'Student',
    teacher: 'Teacher',
    leader: 'Coordinator',
    loginButton: 'Enter System',
    registerButton: 'Register Now',
    parentName: 'Guardian Name',
    parentEmail: 'Guardian Email',
    gdprNotice: 'In compliance with GDPR, parental consent is required for users under 16.',
    mfaCode: 'OTP Code (sent via email)',
    verify: 'Verify Identity',
    dashboard: 'Dashboard',
    bookClass: 'Book Your Classes',
    myClasses: 'My Activities',
    availableClasses: 'Student Requests',
    claim: 'Take Charge',
    notes: 'Log / Notes',
    announcements: 'Notice Board',
    newAnnouncement: 'New Notice',
    send: 'Publish',
    logout: 'Disconnect',
    selectDate: 'Choose Date',
    selectSubject: 'Choose Subject',
    noClasses: 'No scheduled activities.',
    booked: 'Booked',
    claimedBy: 'Teacher:',
    subject: 'Subject',
    date: 'Date',
    saveNotes: 'Save to Log',
    loading: 'Processing...',
    adminPanel: 'Administration',
    manageLeaders: 'Manage Coordinators',
    promoteToLeader: 'Appoint Coordinator',
    demoteLeader: 'Remove Coordinator',
    isLeader: 'Coordinator',
    reports: 'Daily Reports',
    printReport: 'Print Report',
    maxSubjects: 'Maximum 2 subjects per day.',
    alreadyBooked: 'You are already booked for this subject today.',
    selectSubjectTitle: 'What do you want to study?',
    availableSlots: 'Available Slots',
    confirmBooking: 'Confirm Booking',
    unclaimed: 'Unclaimed',
    generatedBy: 'Generated by Doposcuola Connect System',
    superAdmin: 'Super Admin',
    cancelBooking: 'Cancel Booking',
    releaseClass: 'Release Class'
  },
  es: {
    welcome: 'Portal Doposcuola',
    login: 'Acceso al Portal',
    register: 'Nueva Inscripción',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    name: 'Nombre Completo',
    phone: 'Teléfono',
    age: 'Edad',
    role: '¿Eres Docente o Alumno?',
    student: 'Alumno',
    teacher: 'Docente',
    leader: 'Coordinador',
    loginButton: 'Entrar al Sistema',
    registerButton: 'Registrarse Ahora',
    parentName: 'Nombre del Tutor',
    parentEmail: 'Email del Tutor',
    gdprNotice: 'En cumplimiento con GDPR, se requiere consentimiento parental para menores de 16.',
    mfaCode: 'Código OTP (enviado por email)',
    verify: 'Verificar Identidad',
    dashboard: 'Tablero',
    bookClass: 'Reservar Clases',
    myClasses: 'Mis Actividades',
    availableClasses: 'Solicitudes de Alumnos',
    claim: 'Asignarme',
    notes: 'Registro / Notas',
    announcements: 'Tablón de Anuncios',
    newAnnouncement: 'Nuevo Aviso',
    send: 'Publicar',
    logout: 'Desconectar',
    selectDate: 'Elegir Fecha',
    selectSubject: 'Elegir Materia',
    noClasses: 'No hay actividades programadas.',
    booked: 'Reservado',
    claimedBy: 'Docente:',
    subject: 'Materia',
    date: 'Fecha',
    saveNotes: 'Guardar en Registro',
    loading: 'Procesando...',
    adminPanel: 'Administración',
    manageLeaders: 'Gestión de Coordinadores',
    promoteToLeader: 'Nombrar Coordinador',
    demoteLeader: 'Remover Coordinador',
    isLeader: 'Coordinador',
    reports: 'Reporte Diario',
    printReport: 'Imprimir Reporte',
    maxSubjects: 'Máximo 2 materias por día.',
    alreadyBooked: 'Ya estás inscrito en esta materia hoy.',
    selectSubjectTitle: '¿Qué quieres estudiar?',
    availableSlots: 'Turnos Disponibles',
    confirmBooking: 'Confirmar Reserva',
    unclaimed: 'Sin Asignar',
    generatedBy: 'Generado por sistema Doposcuola Connect',
    superAdmin: 'Super Admin',
    cancelBooking: 'Cancelar Reserva',
    releaseClass: 'Liberar Clase'
  },
  fr: {
    welcome: 'Portail Doposcuola',
    login: 'Connexion Portail',
    register: 'Nouvelle Inscription',
    email: 'Adresse Email',
    password: 'Mot de passe',
    name: 'Nom Complet',
    phone: 'Téléphone',
    age: 'Âge',
    role: 'Êtes-vous Enseignant ou Élève ?',
    student: 'Élève',
    teacher: 'Enseignant',
    leader: 'Coordinateur',
    loginButton: 'Entrer dans le système',
    registerButton: 'S\'inscrire maintenant',
    parentName: 'Nom du Tuteur',
    parentEmail: 'Email du Tuteur',
    gdprNotice: 'Conformément au RGPD, le consentement parental est requis pour les moins de 16 ans.',
    mfaCode: 'Code OTP (envoyé par email)',
    verify: 'Vérifier l\'identité',
    dashboard: 'Tableau de bord',
    bookClass: 'Réserver vos cours',
    myClasses: 'Mes Activités',
    availableClasses: 'Demandes des élèves',
    claim: 'Prendre en charge',
    notes: 'Registre / Notes',
    announcements: 'Tableau d\'affichage',
    newAnnouncement: 'Nouvel Avis',
    send: 'Publier',
    logout: 'Déconnexion',
    selectDate: 'Choisir la date',
    selectSubject: 'Choisir la matière',
    noClasses: 'Aucune activité prévue.',
    booked: 'Réservé',
    claimedBy: 'Enseignant :',
    subject: 'Matière',
    date: 'Date',
    saveNotes: 'Enregistrer au registre',
    loading: 'Traitement...',
    adminPanel: 'Administration',
    manageLeaders: 'Gérer les Coordinateurs',
    promoteToLeader: 'Nommer Coordinateur',
    demoteLeader: 'Retirer Coordinateur',
    isLeader: 'Coordinateur',
    reports: 'Rapport Quotidien',
    printReport: 'Imprimer le Rapport',
    maxSubjects: 'Maximum 2 matières par jour.',
    alreadyBooked: 'Vous êtes déjà inscrit à cette matière aujourd\'hui.',
    selectSubjectTitle: 'Que voulez-vous étudier ?',
    availableSlots: 'Créneaux Disponibles',
    confirmBooking: 'Confirmer la Réservation',
    unclaimed: 'Non Attribué',
    generatedBy: 'Généré par le système Doposcuola Connect',
    superAdmin: 'Super Admin',
    cancelBooking: 'Annuler la réservation',
    releaseClass: 'Libérer le cours'
  },
  de: {
    welcome: 'Doposcuola Portal',
    login: 'Portal Login',
    register: 'Neue Registrierung',
    email: 'E-Mail-Adresse',
    password: 'Passwort',
    name: 'Vollständiger Name',
    phone: 'Telefonnummer',
    age: 'Alter',
    role: 'Sind Sie Lehrer oder Schüler?',
    student: 'Schüler',
    teacher: 'Lehrer',
    leader: 'Koordinator',
    loginButton: 'System betreten',
    registerButton: 'Jetzt registrieren',
    parentName: 'Name des Erziehungsberechtigten',
    parentEmail: 'E-Mail des Erziehungsberechtigten',
    gdprNotice: 'Gemäß DSGVO ist für unter 16-Jährige die Zustimmung der Eltern erforderlich.',
    mfaCode: 'OTP-Code (per E-Mail gesendet)',
    verify: 'Identität überprüfen',
    dashboard: 'Dashboard',
    bookClass: 'Kurse buchen',
    myClasses: 'Meine Aktivitäten',
    availableClasses: 'Schüleranfragen',
    claim: 'Übernehmen',
    notes: 'Logbuch / Notizen',
    announcements: 'Schwarzes Brett',
    newAnnouncement: 'Neue Mitteilung',
    send: 'Veröffentlichen',
    logout: 'Abmelden',
    selectDate: 'Datum wählen',
    selectSubject: 'Fach wählen',
    noClasses: 'Keine Aktivitäten geplant.',
    booked: 'Gebucht',
    claimedBy: 'Lehrer:',
    subject: 'Fach',
    date: 'Datum',
    saveNotes: 'Im Logbuch speichern',
    loading: 'Verarbeitung...',
    adminPanel: 'Verwaltung',
    manageLeaders: 'Koordinatoren verwalten',
    promoteToLeader: 'Koordinator ernennen',
    demoteLeader: 'Koordinator entfernen',
    isLeader: 'Koordinator',
    reports: 'Tagesbericht',
    printReport: 'Bericht drucken',
    maxSubjects: 'Maximal 2 Fächer pro Tag.',
    alreadyBooked: 'Sie sind heute bereits für dieses Fach angemeldet.',
    selectSubjectTitle: 'Was möchten Sie lernen?',
    availableSlots: 'Verfügbare Plätze',
    confirmBooking: 'Buchung bestätigen',
    unclaimed: 'Nicht zugewiesen',
    generatedBy: 'Generiert vom Doposcuola Connect System',
    superAdmin: 'Super Admin',
    cancelBooking: 'Buchung stornieren',
    releaseClass: 'Klasse freigeben'
  }
};
